// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.1
// source: drpc/drpc.proto

package drpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DPointers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Successor string `protobuf:"bytes,2,opt,name=successor,proto3" json:"successor,omitempty"`
	D         string `protobuf:"bytes,3,opt,name=d,proto3" json:"d,omitempty"`
}

func (x *DPointers) Reset() {
	*x = DPointers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drpc_drpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DPointers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DPointers) ProtoMessage() {}

func (x *DPointers) ProtoReflect() protoreflect.Message {
	mi := &file_drpc_drpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DPointers.ProtoReflect.Descriptor instead.
func (*DPointers) Descriptor() ([]byte, []int) {
	return file_drpc_drpc_proto_rawDescGZIP(), []int{0}
}

func (x *DPointers) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DPointers) GetSuccessor() string {
	if x != nil {
		return x.Successor
	}
	return ""
}

func (x *DPointers) GetD() string {
	if x != nil {
		return x.D
	}
	return ""
}

type DBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bid string `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`
}

func (x *DBlock) Reset() {
	*x = DBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drpc_drpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBlock) ProtoMessage() {}

func (x *DBlock) ProtoReflect() protoreflect.Message {
	mi := &file_drpc_drpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBlock.ProtoReflect.Descriptor instead.
func (*DBlock) Descriptor() ([]byte, []int) {
	return file_drpc_drpc_proto_rawDescGZIP(), []int{1}
}

func (x *DBlock) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

type DBlocks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blocks []*DBlock `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
}

func (x *DBlocks) Reset() {
	*x = DBlocks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drpc_drpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBlocks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBlocks) ProtoMessage() {}

func (x *DBlocks) ProtoReflect() protoreflect.Message {
	mi := &file_drpc_drpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBlocks.ProtoReflect.Descriptor instead.
func (*DBlocks) Descriptor() ([]byte, []int) {
	return file_drpc_drpc_proto_rawDescGZIP(), []int{2}
}

func (x *DBlocks) GetBlocks() []*DBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type DPeer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DPeer) Reset() {
	*x = DPeer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drpc_drpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DPeer) ProtoMessage() {}

func (x *DPeer) ProtoReflect() protoreflect.Message {
	mi := &file_drpc_drpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DPeer.ProtoReflect.Descriptor instead.
func (*DPeer) Descriptor() ([]byte, []int) {
	return file_drpc_drpc_proto_rawDescGZIP(), []int{3}
}

func (x *DPeer) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *DPeer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DEmpty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DEmpty) Reset() {
	*x = DEmpty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drpc_drpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DEmpty) ProtoMessage() {}

func (x *DEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_drpc_drpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DEmpty.ProtoReflect.Descriptor instead.
func (*DEmpty) Descriptor() ([]byte, []int) {
	return file_drpc_drpc_proto_rawDescGZIP(), []int{4}
}

var File_drpc_drpc_proto protoreflect.FileDescriptor

var file_drpc_drpc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x64, 0x72, 0x70, 0x63, 0x2f, 0x64, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x22, 0x47, 0x0a, 0x09, 0x44, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x72, 0x12, 0x0c, 0x0a, 0x01, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x64, 0x22,
	0x1a, 0x0a, 0x06, 0x44, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x69, 0x64, 0x22, 0x2e, 0x0a, 0x07, 0x44,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x23, 0x0a, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x52, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x22, 0x2b, 0x0a, 0x05, 0x44,
	0x50, 0x65, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x08, 0x0a, 0x06, 0x44, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x32, 0xbc, 0x01, 0x0a, 0x07, 0x44, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x2f,
	0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73,
	0x12, 0x0e, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73,
	0x1a, 0x0b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12,
	0x2c, 0x0a, 0x0e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x12, 0x0b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x1a, 0x0b,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x24, 0x0a,
	0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x0a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x44,
	0x50, 0x65, 0x65, 0x72, 0x1a, 0x0b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x0b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x0c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x22,
	0x00, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6d, 0x61, 0x68, 0x6d, 0x65, 0x64, 0x6e, 0x61, 0x62, 0x69, 0x6c, 0x31, 0x30, 0x39, 0x2f, 0x6b,
	0x6f, 0x6f, 0x72, 0x64, 0x65, 0x2d, 0x6f, 0x76, 0x65, 0x72, 0x6c, 0x61, 0x79, 0x2f, 0x64, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x64, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_drpc_drpc_proto_rawDescOnce sync.Once
	file_drpc_drpc_proto_rawDescData = file_drpc_drpc_proto_rawDesc
)

func file_drpc_drpc_proto_rawDescGZIP() []byte {
	file_drpc_drpc_proto_rawDescOnce.Do(func() {
		file_drpc_drpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_drpc_drpc_proto_rawDescData)
	})
	return file_drpc_drpc_proto_rawDescData
}

var file_drpc_drpc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_drpc_drpc_proto_goTypes = []interface{}{
	(*DPointers)(nil), // 0: rpc.DPointers
	(*DBlock)(nil),    // 1: rpc.DBlock
	(*DBlocks)(nil),   // 2: rpc.DBlocks
	(*DPeer)(nil),     // 3: rpc.DPeer
	(*DEmpty)(nil),    // 4: rpc.DEmpty
}
var file_drpc_drpc_proto_depIdxs = []int32{
	1, // 0: rpc.DBlocks.blocks:type_name -> rpc.DBlock
	0, // 1: rpc.DServer.UpdatePointers:input_type -> rpc.DPointers
	1, // 2: rpc.DServer.BroadcastBlock:input_type -> rpc.DBlock
	3, // 3: rpc.DServer.Connect:input_type -> rpc.DPeer
	4, // 4: rpc.DServer.GetLocalBlock:input_type -> rpc.DEmpty
	4, // 5: rpc.DServer.UpdatePointers:output_type -> rpc.DEmpty
	4, // 6: rpc.DServer.BroadcastBlock:output_type -> rpc.DEmpty
	4, // 7: rpc.DServer.Connect:output_type -> rpc.DEmpty
	2, // 8: rpc.DServer.GetLocalBlock:output_type -> rpc.DBlocks
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_drpc_drpc_proto_init() }
func file_drpc_drpc_proto_init() {
	if File_drpc_drpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_drpc_drpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DPointers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drpc_drpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drpc_drpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBlocks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drpc_drpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DPeer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drpc_drpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DEmpty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_drpc_drpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_drpc_drpc_proto_goTypes,
		DependencyIndexes: file_drpc_drpc_proto_depIdxs,
		MessageInfos:      file_drpc_drpc_proto_msgTypes,
	}.Build()
	File_drpc_drpc_proto = out.File
	file_drpc_drpc_proto_rawDesc = nil
	file_drpc_drpc_proto_goTypes = nil
	file_drpc_drpc_proto_depIdxs = nil
}
